### Successful Login
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "salainen"
}

### Alternate Login
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "testUser",
  "password": "testPassword"
}

### Get all users
GET http://localhost:3001/api/users
Content-Type: application/json

### Create new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "testUser",
  "name": "Test User",
  "password": "testPassword"
}

### Create new note by logged in user
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNGMyMGYyNmZlMTkyYTI5MzM1OTc5NCIsImlhdCI6MTY2NTk1MzIzM30.AvbeglTS-_jU5xdda4d_FnkE8itU6nQImjILcr8lybM

{
  "title": "Create new note by logged in user",
  "content": "Single Page Apps use token authentication",
  "important": true,
  "url": "http://www.google.com"
}

### Delete note by correct user
DELETE  http://localhost:3001/api/blogs/634c3ae0fb1252354d26ca34
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNGMyMGYyNmZlMTkyYTI5MzM1OTc5NCIsImlhdCI6MTY2NTk1MzIzM30.AvbeglTS-_jU5xdda4d_FnkE8itU6nQImjILcr8lybM

### Delete note by incorrect user
DELETE  http://localhost:3001/api/blogs/634c3ae0fb1252354d26ca34
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWQiOiI2MzRkNTRhMDY4ODQ1YWNkMGZlMmZiMDkiLCJpYXQiOjE2NjYwMTI1MDB9.SyktkbdBNrAkBQ2qivhVVnrrVFfv5awPLcn6yyZrW9E