POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY3MTQ2MTQzMX0.jTXrhgPLAoR16RQm-dh_Ot2TyGGppSXYGb1i6rAgNgI

{
  "author": "user",
  "url": "user@gmail.com",
  "title": "User blog post",
  "likes": 50,
  "year": 1995
}